from typing import Final

MAX_ANIMATION_TICKS: Final = 10
MAX_FPS: Final = 10
WIDTH: Final = 190
HEIGHT: Final = 480
BG_COLOR: Final = (255, 255, 255)
GRAVITY: Final = 1
PLAYER_SPEED: Final = 1
PLAYER_JUMP_POWER: Final = 1
PLAYER_NORMAL_FRICTION: Final = 0.9
PLAYER_ON_GROUND_FRICTION: Final = 0.6
PLAYER_MOVE_CHECK_RANGE: Final = 5
PLAYER_ANIMATION_TICKS: Final = 10
PLAYER_SIZE: Final = (32, 32)
